List<String> correctResponses = [
  "Correct!",
  "Well done!",
  "You're on fire!",
  "Fantastic!",
  "You nailed it!",
  "Brilliant!",
  "Excellent choice!",
  "You got it right!",
  "Superb!",
  "Amazing!",
];
List<String> wrongResponses = [
  "Wrong!",
  "Wrong Answer :(",
  "Hard luck.",
  "Oops! Don't worry, let's try again.",
  "Hmm, not quite there. You've got this!",
  "Uh-oh! Keep going, you'll get it next time!",
  "Not quite, but you're getting closer!",
  "That's not it, but keep trying!",
  "Hmm, not the one, but you're learning!",
  "Close, but not quite! Keep pushing!"
];

List<String> nextPatternQuestions = [
  "What pattern do you anticipate in the next graph?",
  "Can you guess the pattern in the upcoming graph?",
  "What pattern do you think will appear next?",
  "Any predictions for the pattern in the next graph?",
  "What's your guess for the pattern in the following graph?",
  "What pattern are you expecting in the next graph?",
  "What do you think the next graph will reveal in terms of pattern?",
  "Care to guess the pattern in the next graph?",
  "What pattern do you foresee in the next graph?",
  "Can you anticipate the pattern in the upcoming graph?",
];

// Map<String, List<Map<String, double>>> patterns = {
//   'HeadShoulders': [
//     {"x": 1, "y": 0},
//     {"x": 2, "y": 2},
//     {"x": 3, "y": 3},
//     {"x": 4, "y": 1},
//     {"x": 5, "y": 5},
//     {"x": 6, "y": 1.5},
//     {"x": 7, "y": 2},
//     {"x": 8, "y": 3},
//     {"x": 9, "y": 2},
//     {"x": 10, "y": 0},
//   ],
//   'DoubleTop': [
//     {"x": 1, "y": 1},
//     {"x": 2, "y": 2},
//     {"x": 3, "y": 3},
//     {"x": 4, "y": 4},
//     {"x": 5, "y": 5},
//     {"x": 6, "y": 3},
//     {"x": 7, "y": 5},
//     {"x": 8, "y": 4},
//     {"x": 9, "y": 3},
//     {"x": 10, "y": 1},
//   ],
//   'DoubleBottom': [
//     {"x": 1, "y": -1},
//     {"x": 2, "y": -2},
//     {"x": 3, "y": -3},
//     {"x": 4, "y": -4},
//     {"x": 5, "y": -5},
//     {"x": 6, "y": -3},
//     {"x": 7, "y": -5},
//     {"x": 8, "y": -4},
//     {"x": 9, "y": -3},
//     {"x": 10, "y": -1},
//   ],
//   'CupHandle': [
//     {"x": 1, "y": 0},
//     {"x": 2, "y": 4},
//     {"x": 3, "y": 2.2},
//     {"x": 4, "y": 2},
//     {"x": 5, "y": 0.8},
//     {"x": 6, "y": 1},
//     {"x": 7, "y": 0.8},
//     {"x": 8, "y": 2},
//     {"x": 9, "y": 2.2},
//     {"x": 10, "y": 4},
//     {"x": 11, "y": 3},
//     {"x": 12, "y": 4},
//     {"x": 13, "y": 6},
//   ],
//   'AscendingTriangle': [
//     {"x": 1, "y": 0},
//     {"x": 2, "y": 8},
//     {"x": 3, "y": 1.5},
//     {"x": 4, "y": 8},
//     {"x": 5, "y": 3.5},
//     {"x": 6, "y": 8},
//     {"x": 7, "y": 5},
//     {"x": 8, "y": 8},
//     {"x": 9, "y": 6},
//     {"x": 10, "y": 12},
//     {"x": 11, "y": 10},
//     {"x": 12, "y": 15},
//   ],
//   'DescendingTriangle': [
//     {"x": 1, "y": 10},
//     {"x": 2, "y": 3},
//     {"x": 3, "y": 9},
//     {"x": 4, "y": 3},
//     {"x": 5, "y": 7},
//     {"x": 6, "y": 3},
//     {"x": 7, "y": 5},
//     {"x": 8, "y": 3},
//     {"x": 9, "y": 3},
//     {"x": 10, "y": 0},
//     {"x": 11, "y": 2},
//     {"x": 12, "y": -1},
//   ],
// };
